services:
  mysql-db:
    image: mysql:8.0
    container_name: skinRoutine-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tngkr5696@#@
      MYSQL_DATABASE: skin
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
