spring:
  application:
    name: skin-service

  profiles:
    default: local

  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

springdoc:
  api-docs:
    path: /v3/api-docs
